spring:
  application:
    name: barista-service
  cloud:
    stream:
      bindings:
        newOrders:
          group: barista-service
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/springbucks?allowPublicKeyRetrieval=true&useSSL=false
    username: springbucks
    password: springbucks
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: spring

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

order:
  barista-prefix: springbucks-

server:
  port: 0
